##### Word Embedding Techniques using Embedding Layer in Keras

#### Libraries USed Tensorflow> 2.0  and keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences 

sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'i am a good boy',
     'i am a good developer',
      'understand the meaning of word',
      'your video are good '
     ]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of word',
 'your video are good ']

In [4]:
len(sent)

7

In [5]:
### vocabulary size
voc_size=10000

#### one Hot Representation 

In [6]:
onehot_repr=[one_hot(word,voc_size) for word in sent ]

In [7]:
print(onehot_repr)

[[824, 3352, 3160, 864], [824, 3352, 3160, 1994], [824, 7638, 3160, 3842], [7157, 7842, 9630, 1302, 4926], [7157, 7842, 9630, 1302, 1236], [6951, 824, 2935, 3160, 2409], [142, 9277, 1423, 1302]]


#### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  824 3352 3160  864]
 [   0    0    0    0  824 3352 3160 1994]
 [   0    0    0    0  824 7638 3160 3842]
 [   0    0    0 7157 7842 9630 1302 4926]
 [   0    0    0 7157 7842 9630 1302 1236]
 [   0    0    0 6951  824 2935 3160 2409]
 [   0    0    0    0  142 9277 1423 1302]]


In [11]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

[[[-0.0379196   0.0347842   0.01843366 -0.01012189  0.02207036
    0.01232777 -0.03688674  0.02285251 -0.03804178 -0.02042508]
  [-0.0379196   0.0347842   0.01843366 -0.01012189  0.02207036
    0.01232777 -0.03688674  0.02285251 -0.03804178 -0.02042508]
  [-0.0379196   0.0347842   0.01843366 -0.01012189  0.02207036
    0.01232777 -0.03688674  0.02285251 -0.03804178 -0.02042508]
  [-0.0379196   0.0347842   0.01843366 -0.01012189  0.02207036
    0.01232777 -0.03688674  0.02285251 -0.03804178 -0.02042508]
  [ 0.03594282 -0.02510544  0.02499712 -0.01157169  0.02387861
    0.01436223  0.01658848 -0.02141076 -0.00331557  0.00684024]
  [ 0.04375633  0.04917337 -0.03316671 -0.02894274 -0.0470754
   -0.03817021  0.02588021 -0.02382292 -0.03014864 -0.0311245 ]
  [ 0.03330034 -0.00219188  0.00268272  0.03550358 -0.01669144
    0.02897343  0.00244975  0.04996845  0.02771808 -0.03270362]
  [-0.04909877  0.01711204 -0.00813807 -0.00984985 -0.00275798
   -0.02093973  0.02616887 -0.00302394  0.0236229

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0,  824, 3352, 3160,  864])

In [17]:
print(model.predict(embedded_docs)[0])

[[-0.0379196   0.0347842   0.01843366 -0.01012189  0.02207036  0.01232777
  -0.03688674  0.02285251 -0.03804178 -0.02042508]
 [-0.0379196   0.0347842   0.01843366 -0.01012189  0.02207036  0.01232777
  -0.03688674  0.02285251 -0.03804178 -0.02042508]
 [-0.0379196   0.0347842   0.01843366 -0.01012189  0.02207036  0.01232777
  -0.03688674  0.02285251 -0.03804178 -0.02042508]
 [-0.0379196   0.0347842   0.01843366 -0.01012189  0.02207036  0.01232777
  -0.03688674  0.02285251 -0.03804178 -0.02042508]
 [ 0.03594282 -0.02510544  0.02499712 -0.01157169  0.02387861  0.01436223
   0.01658848 -0.02141076 -0.00331557  0.00684024]
 [ 0.04375633  0.04917337 -0.03316671 -0.02894274 -0.0470754  -0.03817021
   0.02588021 -0.02382292 -0.03014864 -0.0311245 ]
 [ 0.03330034 -0.00219188  0.00268272  0.03550358 -0.01669144  0.02897343
   0.00244975  0.04996845  0.02771808 -0.03270362]
 [-0.04909877  0.01711204 -0.00813807 -0.00984985 -0.00275798 -0.02093973
   0.02616887 -0.00302394  0.0236229   0.00448553]]